### ISSUE TITLE
Use config file

### ISSUE THREAD

**Issue by anton-johansson** [anton-johansson/callback-service#1]
```yaml
http:
  session:
    secret: abc123
  accessAllowOrigin: http://localhost:3000
ui:
  suggestionPath: :1234
database:
  fileName: /var/callback-service/database.json
ldap:
  domain: ...
  url: ...
  caPath: /etc/callback-service/ca.crt
  searchBase: DC=example,DC=local
  attributes:
    username: sAMAccountName
    name: cn
    email: mail
```
